---
abstract: "Interface to ExactTarget's API."
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  HTML::Entities: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  Params::Util: 0
  SOAP::Lite: 0.71
  Test::Deep: 0
  Test::More: 0.94
  Text::Unaccent: 0
  Try::Tiny: 0
  URI::Escape: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-ExactTarget
provides:
  Email::ExactTarget:
    file: lib/Email/ExactTarget.pm
    version: v1.2.1
  Email::ExactTarget::Subscriber:
    file: lib/Email/ExactTarget/Subscriber.pm
    version: v1.2.1
  Email::ExactTarget::SubscriberOperations:
    file: lib/Email/ExactTarget/SubscriberOperations.pm
    version: v1.2.1
requires:
  perl: 5.006
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v1.2.1
